### ISSUE TITLE
Интеграция из дискорда в гмод

### ISSUE THREAD

**Issue by Sh1ro-Sam4** [bewflast/GDiscord#1]
конфуз, пошел нахуй

**Comment by Sh1ro-Sam4** [comment]
Сервер стоит на BaseWars режиме. Подскажи что может быть не так? Чат - easychat

**Comment by bewflast** [comment]
Прошу прощения за задержку

После некоторых нововведений, Дискорду нужен интент Message content

Просто включи этот  
![chrome_Sv0rxMD5Zd](https://user-images.githubusercontent.com/68069182/195731293-30855e26-2cbe-46b2-a2c7-aaa6bd20276d.jpg)

**Comment by bewflast** [comment]
дай знать, если решил проблему

**Comment by bewflast** [comment]
солвед как говорится
